# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metachart < Formula
  desc ""
  homepage "https://github.com/iponweb/metachart"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iponweb/metachart/releases/download/v0.1.0/metachart_0.1.0_Darwin_arm64.tar.gz"
      sha256 "df2907f8480e90aca2b9479487831884a7f2c01dd01a82e957f9d7cbd9b3a146"

      def install
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iponweb/metachart/releases/download/v0.1.0/metachart_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "06515eddf0fb81f2d6d21abab23cf4f232bc4ce5c132c67c03017f6b702acafe"

      def install
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iponweb/metachart/releases/download/v0.1.0/metachart_0.1.0_Linux_arm64.tar.gz"
      sha256 "3d8ab95d92224deba2e02f59f7f56344df2e6262d940ada0fb6d96146a7fb288"

      def install
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iponweb/metachart/releases/download/v0.1.0/metachart_0.1.0_Linux_x86_64.tar.gz"
      sha256 "76aa89e19e958f0e7a198d376fc3503a41d9ae1e03be949f01b969e24abe3452"

      def install
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
  end

  test do
    system "#{bin}/metachart version"
  end
end
