# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metachart < Formula
  desc ""
  homepage "https://github.com/iponweb/metachart"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/iponweb/metachart/releases/download/v0.1.2/metachart_Darwin_arm64.tar.gz"
      sha256 "61bf1ec3ac52a37272532b3002b6d0011a19f79701f36b201643d2bfd69598f8"

      def install
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iponweb/metachart/releases/download/v0.1.2/metachart_Darwin_x86_64.tar.gz"
      sha256 "4bbcd3531e83e91997b4ffd7a73b74901fc9219a59745ab12007f21a7e30b320"

      def install
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iponweb/metachart/releases/download/v0.1.2/metachart_Linux_arm64.tar.gz"
      sha256 "14fd3d51b6cfc9b36712ecb7b51d1c0ee5c155e70c7a05ac5f5246865e263575"

      def install
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/iponweb/metachart/releases/download/v0.1.2/metachart_Linux_x86_64.tar.gz"
      sha256 "19073d05296e794cab1fcfa7f49ab59c3e2bf805f0cc07b7bf7b69c190aa07be"

      def install
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
  end

  test do
    system "#{bin}/metachart version"
  end
end
