# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metachart < Formula
  desc ""
  homepage "https://github.com/iponweb/metachart"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iponweb/metachart/releases/download/v0.3.0/metachart_Darwin_x86_64.tar.gz"
      sha256 "08111216291794cd7efa15f130254c41103ea2a392a8e259228f77ead6310bd7"

      define_method(:install) do
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iponweb/metachart/releases/download/v0.3.0/metachart_Darwin_arm64.tar.gz"
      sha256 "7ff74c2ae9cd27010773889723735293147ef3447b7c56a93f9cd97d01d4b7ef"

      define_method(:install) do
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iponweb/metachart/releases/download/v0.3.0/metachart_Linux_x86_64.tar.gz"
      sha256 "1514b3187f655763d250dd9ce8adb49ad6e55245f68a1e76635d13277b51b2e7"
      define_method(:install) do
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iponweb/metachart/releases/download/v0.3.0/metachart_Linux_arm64.tar.gz"
      sha256 "a23cfa65a51c21613b020f467a168423dceb22d4b3f35e6a3d3002dbc20a3663"
      define_method(:install) do
        bin.install "metachart"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "bash")
        (bash_completion/"metachart").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"metachart", "completion", "zsh")
        (zsh_completion/"_metachart").write output
      end
    end
  end

  test do
    system "#{bin}/metachart version"
  end
end
